alumnos/urls.py
from django.urls import path

from alumnos.views.alumnos import AlumnosListView, AlumnoCreateView, AlumnoUpdateView, AlumnoDelete, \
    AlumnosCompletoListView
from alumnos.views.base import IndexView

app_name = 'alumnos'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('alumnos/list/', AlumnosListView.as_view(), name='alumnos_list'),
    path('alumnos/new/', AlumnoCreateView.as_view(), name='alumnos_new'),
    path('alumnos/edit/<int:pk>/', AlumnoUpdateView.as_view(), name='alumnos_edit'),
    path('alumnos/del/', AlumnoDelete.as_view(), name='alumnos_delete'),

    path('alumnos/lista/completa/', AlumnosCompletoListView.as_view(), name='alumnos_lista_completa')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('alumnos.urls')),
]

alumnos/models.py
from django.db import models

# Create your models here.


class Alumno(models.Model):
    nombre = models.CharField(max_length=300, verbose_name='Nombre')
    nota = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Promedio')

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Alumno'
        verbose_name_plural = 'Alumnos'
        ordering = ['nombre']

alumnos/forms.py
from django.forms import *

from alumnos.models import Alumno


class AlumnoForm(ModelForm):

    class Meta:
        model = Alumno
        fields = '__all__'

        widgets = {
            'nombre': TextInput(
                attrs={
                    'placeholder': 'Ingrese el nombre del alumno',
                }
            ),
        }

alumnos/views/alumnos.py
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.base import View

from alumnos.forms import AlumnoForm
from alumnos.models import Alumno


class AlumnosListView(ListView):
    model = Alumno
    template_name = 'alumnos/lista.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Alumnos'
        context['formpage'] = reverse_lazy('alumnos:alumnos_new')
        return context


class AlumnoCreateView(CreateView):
    model = Alumno
    form_class = AlumnoForm
    template_name = 'alumnos/form.html'
    success_url = reverse_lazy('alumnos:alumnos_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Alumnos'
        context['listpage'] = self.success_url
        context['action_form'] = 'add'
        return context

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action_form']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                else:
                    data['error'] = form.errors
            else:
                data['error'] = 'Action invalid'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)


class AlumnoUpdateView(UpdateView):
    model = Alumno
    form_class = AlumnoForm
    template_name = 'alumnos/form.html'
    success_url = reverse_lazy('alumnos:alumnos_list')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Alumnos'
        context['listpage'] = self.success_url
        context['action_form'] = 'edit'
        return context

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action_form']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                else:
                    data['error'] = form.errors
            else:
                data['error'] = 'Action invalid'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)


class AlumnoDelete(View):
    def post(self, request, *args, **kwargs):
        data = {}
        try:
            cate = Alumno.objects.get(pk=request.POST['id'])
            cate.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)


class AlumnosCompletoListView(ListView):
    model = Alumno
    template_name = 'alumnos/lista_completa.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Alumnos'
        return context

alumnos/views/base.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'base.html'

alumnos/templates/alumnos/form.html
{% extends 'base.html' %}

{% load static %}

{% block actions %}
    <button type="submit" form="main_form" class="waves-effect waves-light btn"><i class="material-icons left">save</i> Guardar</button>
    <a href="{{ listpage }}" class="waves-effect waves-light btn"><i class="material-icons left">cancel</i> Cancelar</a>
{% endblock %}

{% block section %}
    <div class="row">
        <form class="col s12" id="main_form">
            {% csrf_token %}
            <input type="hidden" name="action_form" value="{{ action_form }}">
            {{ form.as_p }}
        </form>
    </div>

{% endblock %}

{% block CSS-extra %}
    <link rel="stylesheet" href="{% static 'lib/sweetalert2/sweetalert2.min.css' %}">
{% endblock %}

{% block JS-extra %}

    <script>
        $('#main_form').on('submit', function (e) {
            e.preventDefault();
            const params = $(this).serializeArray();
            $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: params,
                dataType: 'json',
            }).done(function (data) {
                if (!data.hasOwnProperty('error')) {
                    let msg = 'Guardado correctamente';
                    {% if action_form == 'edit' %}
                        msg = 'Modificado correctamente';
                    {% endif %}
                    message_info(msg, '{{ listpage }}');
                    return false;
                }
                message_error(data.error);
            }).fail(function (jqXHR, textStatus, errorThrown) {
                console.error(textStatus + ': ' + errorThrown);
            }).always(function (data) {
            });
        });
    </script>
{% endblock %}

alumnos/templates/alumnos/lista.html
{% extends 'list.html' %}

{% load static %}

{% block actions %}
    <a href="{{ formpage }}" class="waves-effect waves-light btn"><i class="material-icons left">add</i> Nuevo</a>
{% endblock %}

{% block thead-row %}
    <th>ID</th>
    <th>Nombre</th>
    <th>Promedio</th>
    <th></th>
{% endblock %}

{% block tbody %}

    {% if object_list %}
        {% for alumno in object_list %}
            <tr>
                <td>{{ alumno.id }}</td>
                <td>{{ alumno.nombre }}</td>
                <td>{{ alumno.nota }}</td>
                <td>
                    <a href="{% url 'alumnos:alumnos_edit' alumno.id %}" class="btn-floating btn-large waves-effect waves-light yellow">
                        <i class="material-icons">edit</i>
                    </a>
                    <a class="btn-floating btn-large waves-effect waves-light red" onclick="Delete({{ alumno.id }})">
                        <i class="material-icons">delete</i>
                    </a>
                </td>
            </tr>
        {% endfor %}
    {% else %}
        <h3>No hay alumnos cargados</h3>
    {% endif %}


{% endblock %}

{% block JS-extra %}

    <script src="{% static 'lib/js-cookie-3.0.0/js.cookie.min.js' %}"></script>

    <script type="application/javascript">
        function Delete(id) {
            var csrftoken = Cookies.get('csrftoken');
            function csrfSafeMethod(method) {
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

            message_question(`¿Seguro quiere eliminar el alumno #${id}?`, function () {
                // función AJAX
                $.ajax({
                    url: "{% url 'alumnos:alumnos_delete' %}",
                    type: "POST",
                    data: {'id': id},
                    dataType: "json",
                }).done(function (data) {
                    if (!data.hasOwnProperty("error")) {
                        message_info('', '', function () {
                            location.reload();
                        });
                        return false;
                    }
                    message_error(data.error);
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    message_error(textStatus + ": " + errorThrown);
                }).always(function (data) {
                })
            })
        }
    </script>
{% endblock %}

alumnos/templates/alumnos/lista_completa.html
{% extends 'list.html' %}

{% block thead-row %}
    <th>ID</th>
    <th>Nombre</th>
    <th>Promedio</th>
    <th>Aprobado</th>
{% endblock %}

{% block tbody %}

    {% if object_list %}
        {% for alumno in object_list %}
            <tr>
                <td>{{ alumno.id }}</td>
                <td>{{ alumno.nombre }}</td>
                <td>{{ alumno.nota }}</td>
                <td>
                    {% if alumno.nota >= 3 and alumno.nota <= 5 %}
                        SI
                    {% endif %}
                    {% if alumno.nota < 3 %}
                        NO
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    {% else %}
        <h3>No hay alumnos cargados</h3>
    {% endif %}


{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Alumnos</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'lib/materializecss/materialize.min.css' %}">

    {% block CSS-extra %}
    {% endblock %}

</head>
<body>

{% include 'navbar.html' %}

<main class="container">

    <h1>{{ title }}</h1>

    <section>
        <div class="actions">
            {% block actions %}
            {% endblock %}
        </div>
        <div class="section">
            {% block section %}
            {% endblock %}
        </div>
    </section>
</main>

<!-- Scripts Base -->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="{% static 'lib/materializecss/materialize.min.js' %}"></script>

<script src="{% static 'lib/sweetalert2/sweetalert2.all.min.js' %}"></script>
<script src="{% static 'js/messages.js' %}"></script>

<script>
    $(document).ready(function () {
        $('.sidenav').sidenav();
    });
</script>

{% block JS-extra %}
{% endblock %}

</body>
</html>

templates/list.html
{% extends 'base.html' %}

{% block section %}
    <table>
        <thead>
        <tr>
            {% block thead-row %}
            {% endblock %}
        </tr>
        </thead>
        <tbody>
        {% block tbody %}
        {% endblock %}
        </tbody>
    </table>
{% endblock %}

templates/navbar.html
<nav>
    <div class="nav-wrapper">
        <a href="{% url 'alumnos:index' %}" class="brand-logo">Alumnos</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'alumnos:alumnos_list' %}">Gestión</a></li>
            <li><a href="{% url 'alumnos:alumnos_lista_completa' %}">Listado</a></li>
        </ul>
    </div>
</nav>

<ul class="sidenav" id="mobile-demo">
    <li><a href="{% url 'alumnos:alumnos_list' %}">Gestión</a></li>
    <li><a href="{% url 'alumnos:alumnos_lista_completa' %}">Listado</a></li>
</ul>